version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/windows/servercore:ltsc2019

    steps:
      - run:
          name: Downloading Essentials
          command: |
            Invoke-WebRequest -Uri https://gitlab.com/chamod12/ngrok-win10-rdp/-/raw/main/Downloads.bat -OutFile Downloads.bat
            cmd /c Downloads.bat

      - run:
          name: Connecting Ngrok Account
          command: ngrok config add-authtoken $NGROK_AUTH_TOKEN

      - run:
          name: Enabling RDP Access
          command: cmd /c Acess.bat

      - run:
          name: Log In To Remote Desktop Protocol
          command: cmd /c startaudio.bat

      - run:
          name: 90-Minute Timeout
          command: timeout /t 5400 /nobreak
          
